---

stages:
  - prepare
  - build
  - release

prepare:5.6:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:5.6
  only:
    - master

prepare:7.0:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.0
  only:
    - master

prepare:7.1:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.1
  only:
    - master

prepare:7.2:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.2
  only:
    - master

prepare:7.3:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.3
  only:
    - master

prepare:7.4:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull dockerwest/php:7.4
  only:
    - master

build:5.6:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 5.6; ./build.sh
  only:
    - master

build:7.0:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.0; ./build.sh
  only:
    - master

build:7.1:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.1; ./build.sh
  only:
    - master

build:7.2:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.2; ./build.sh
  only:
    - master

build:7.3:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.3; ./build.sh
  only:
    - master

build:7.4:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.4; ./build.sh
  only:
    - master

release:5.6:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:5.6
  only:
    - master

release:7.0:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:7.0
  only:
    - master

release:7.1:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:7.1
  only:
    - master

release:7.2:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:7.2
  only:
    - master

release:7.3:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:7.3
  only:
    - master

release:7.4:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php-pimcore:7.4
  only:
    - master
